version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "lumino-php-app"
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Nothing to install for plain PHP
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 099199746132.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "Build started"
      - echo "Building the  PHP Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 099199746132.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo "Pushing PHP image to ECR..."
      - docker push 099199746132.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"lumino-php-app","imageUri":"%s"}]' "099199746132.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG" > imagedefinitions.json

 
artifacts:
  files:
    - imagedefinitions.json
